### ISSUE TITLE
Hash password automatically

### ISSUE THREAD

**Issue by filcole** [ScottHelme/AlexaNissanLeaf#4]
At the moment the password has to be grabbed from a fiddler trace.  Would be good to hash that password within the app.

**Comment by ScottHelme** [comment]
I'm almost there on this but for some reason the encrypted value doesn't come out quite right. Got a second to look at it?

https://github.com/ScottHelme/AlexaNissanLeaf/tree/encrypt-password

**Comment by ScottHelme** [comment]
Fixed with: https://github.com/ScottHelme/AlexaNissanLeaf/commit/1c58d30367fbb1bf3d91b784ae9dceb99a81074a
