### ISSUE TITLE
UpdateIntent provides no feedback to the user

### ISSUE THREAD

**Issue by filcole** [ScottHelme/AlexaNissanLeaf#7]
Confused as to the purpose of this intent.  It would be good to combine it with the climate control status, so that it says the whole status of the car.

**Comment by ScottHelme** [comment]
There is no feedback to provide other than that the update has been requested and new data is being downloaded from the car. I'd like to refrain from incorporating this into other intents as it is a slow process that often fails and would negatively impact the climate control, for example. It is a distinct action so has a distinct intent.
